latex_template = r"""
\documentclass[12pt]{article}
\usepackage{geometry}
\geometry{margin=1in}
\usepackage{enumitem}
\begin{document}

\begin{center}
    {\LARGE \textbf{Mock Interview for {{ name }}}}\\[1em]
    \textbf{Career Field:} {{ career_field }}\\
    \textbf{Goal/Role:} {{ goal }}
\end{center}

\vspace{1em}
\textbf{Introduction:}

{{ intro }}

\vspace{1em}
\textbf{Sample Interview Questions:}
\begin{enumerate}[leftmargin=*, label={\textbf{Q\arabic*:}}]
{% for q in questions %}
    \item {{ q.question }}
    \begin{itemize}
        \item \textit{Model Answer / Tip:} {{ q.tip }}
    \end{itemize}
{% endfor %}
\end{enumerate}

\vfill
\begin{flushright}
\textit{Generated by GenAI Career Coach.}
\end{flushright}

\end{document}
"""
